Feature/cf 1254 consumer offset resets
dhlparcel/dhl-infra-kafka-tools pull request #2
Opened 2024-08-02 09:49 UTC by sbinda-dhl

2024-08-02 09:52 UTC, sbinda-dhl commented
See tests with options earliest and latest in:
https://dev.azure.com/dhlnl/Infrastructure/_build?definitionId=1161&_a=summary

2024-08-02 12:30 UTC, tonswart commented
I'm missing the pipeline to deploy the helm templates to AKS.

And the shell script in the AKS pod has `read` statements which I suppose do not run in a non interactive azure devops pipeline.

2024-08-09 06:49 UTC, tonswart commented on devops/deploy-helm-chart.yml
> +  - name: helmChartPath
Is dit een parameter die je wilt aanpassen als je de pipeline wilt starten?? Lijkt mij meer een variable.

2024-08-09 06:49 UTC, tonswart commented on devops/deploy-helm-chart.yml
> +  - name: k8sNamespace
Zouden we naar een andere namespace willen deployen dan de default? Klinkt ook meer als een variable.

2024-08-09 06:49 UTC, tonswart commented on devops/reset-consumergroup-offset-by-csv-file.yml
> +  # - name: performDryRun
Kan deze commented code weg?

2024-08-09 06:49 UTC, tonswart commented on devops/reset-consumergroup-offset-by-datetime.yml
> +  # - name: performDryRun
Kan weg

2024-08-09 06:49 UTC, tonswart commented on helm-charts/kafka-tools-controller/templates/cm-scripts.yaml
> +    function_call=$1; shift; $function_call "$@"
Wat doet function_call precies?

2024-08-09 11:55 UTC, sbinda-dhl commented on devops/deploy-helm-chart.yml
> +  - name: k8sNamespace
DIt willen we nog wel flexibel kunnen doen op runtime.

2024-08-09 12:00 UTC, sbinda-dhl commented on helm-charts/kafka-tools-controller/templates/cm-scripts.yaml
> +    function_call=$1; shift; $function_call "$@"
hiermee kun je een functie in het script aanroepen zonder eerste te sourcen en variabel aantal params meegeven.
volgorde is scriptnaam / functie / params voor betreffende functie 

vb: set_offset_from_file funcie:

./reset-consumergroup-offset.sh set_offset_from_file() [CONSUMER_GROUP] [BASE_PATH] [FILE_NAME]

2024-08-09 12:01 UTC, sbinda-dhl commented on devops/deploy-helm-chart.yml
> +  - name: helmChartPath
fixed

2024-08-09 12:01 UTC, sbinda-dhl commented on devops/reset-consumergroup-offset-by-csv-file.yml
> +  # - name: performDryRun
fixed

2024-08-09 12:14 UTC, tonswart approved these changes

2024-08-19 11:47 UTC, Ronaldschouw requested changes

2024-08-19 11:47 UTC, Ronaldschouw commented on helm-charts/kafka-tools-controller/values-accept.yaml
De verwijzingen naar poort 443 mogen eruit, deze worden niet gebruikt

2024-08-19 11:47 UTC, Ronaldschouw commented on helm-charts/kafka-tools-controller/values-prod.yaml
De verwijzingen naar poort 443 mogen eruit, deze worden niet gebruikt

2024-08-19 11:47 UTC, Ronaldschouw commented on helm-charts/kafka-tools-controller/values-test.yaml
De verwijzingen naar poort 443 mogen eruit, deze worden niet gebruikt

2024-08-21 07:46 UTC, Ronaldschouw approved these changes

2024-08-21 07:49 UTC, merged